app/app/src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('management_system.urls')),
    path('accounts', include("django.contrib.auth.urls"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/app/src/management_system/urls.py
from django.urls import path
from . import views as app_views

app_name = "management_system"

urlpatterns = [
    path('', app_views.MainPageView.as_view(), name='main_page'),
    path('login/', app_views.AppLoginView.as_view(), name='login'),
    path('logout/', app_views.AppLogoutView.as_view(), name='logout'),
    path('registration/', app_views.RegisterView.as_view(), name='registration'),
    path('meeting/', app_views.MeetingListView.as_view(), name='meeting'),
    path('meeting/create/', app_views.MeetingCreateView.as_view(), name='meeting_create'),
    path('meeting/<uuid:pk>/', app_views.MeetingDetailView.as_view(), name='meeting_detail'),
    path('task/', app_views.TaskListView.as_view(), name='task'),
    path('task/create/', app_views.TaskCreateView.as_view(), name='task_create'),
    path('task/<uuid:pk>/', app_views.TaskDetailView.as_view(), name='task_detail'),
    path('team/', app_views.TeamListView.as_view(), name='team'),
    path('team/create/', app_views.TeamCreateView.as_view(), name='team_create'),
    path('team/<uuid:pk>/', app_views.TeamDetailView.as_view(), name='team_detail'),
    path('evaluation/', app_views.EvaluationListView.as_view(), name='evaluation'),
    path('evaluation/create/', app_views.EvaluationCreateView.as_view(), name='evaluation_create'),
    path('evaluation/<uuid:pk>/', app_views.EvaluationDetailView.as_view(), name='evaluation_detail'),
]

app/app/src/management_system/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User, Meeting, Team, Task, Evaluation, UserTeam, UserMeeting
from django import forms


class CheckReadOnlyMixin(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        readonly = kwargs.pop('readonly', False)
        super().__init__(*args, **kwargs)
        if readonly:
            for field_name, field in self.fields.items():
                field.widget.attrs['disabled'] = 'disabled'


class RegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'patronymic']


class MeetingForm(CheckReadOnlyMixin):
    class Meta:
        model = Meeting
        fields = ["name", "comments", "day", "time"]


class MeetingMemberForm(CheckReadOnlyMixin):
    class Meta:
        model = UserMeeting
        exclude = ()


MeetingMemberFormSet = forms.inlineformset_factory(Meeting, UserMeeting, form=MeetingMemberForm)


class TeamForm(CheckReadOnlyMixin):
    class Meta:
        model = Team
        fields = ["name"]


class TeamMemberForm(CheckReadOnlyMixin):
    class Meta:
        model = UserTeam
        exclude = ()


TeamMemberFormSet = forms.inlineformset_factory(Team, UserTeam, form=TeamMemberForm)


class TaskForm(CheckReadOnlyMixin):
    class Meta:
        model = Task
        fields = ["name", "description", "status", "comments",
                  "deadline", "executor"]


class EvaluationForm(CheckReadOnlyMixin):
    class Meta:
        model = Evaluation
        fields = ["user", "task", "mark"]

app/app/src/management_system/views.py
from django.db import transaction
from django.db.models import Avg, Func, Q
from django.db.models.functions import TruncMonth
from django.views import View
from django.views.generic import FormView, DetailView, CreateView
from django.views.generic.edit import ModelFormMixin
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from django.contrib.auth.models import AnonymousUser
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from datetime import date

from .models import Meeting, Task, Team, UserTeam, Evaluation
from .forms import (RegisterForm, MeetingForm, TeamForm, TaskForm, EvaluationForm,
                    TeamMemberFormSet, MeetingMemberFormSet)


class DateToChar(Func):
    function = 'TO_CHAR'
    template = "%(function)s(%(expressions)s, 'YYYY-MM')"


class AppLoginView(LoginView):
    template_name = 'auth/login.html'
    redirect_authenticated_user = True
    next_page = reverse_lazy("management_system:main_page")


class AppLogoutView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect("management_system:login")


class RegisterView(FormView):
    form_class = RegisterForm
    template_name = 'auth/registration.html'
    success_url = reverse_lazy("management_system:main_page")

    def form_valid(self, form):
        form.instance.role = 'worker'
        user = form.save()
        login(self.request, user)
        return super().form_valid(form)


class MainPageView(View):
    def get(self, request, *args, **kwargs):
        if not hasattr(request, "user") or isinstance(request.user, AnonymousUser):
            return redirect("management_system:login")
        return render(request, 'base.html')


class MeetingListView(View):
    def get(self, request, *args, **kwargs):
        if not hasattr(request, "user") or isinstance(request.user, AnonymousUser):
            return redirect("management_system:login")
        user_meetings = Meeting.objects.filter(meeting_members__user=request.user)
        context = {"meetings": user_meetings}
        return render(request, 'management_system/list/meeting_list.html', context=context)


class MeetingDetailView(ModelFormMixin, DetailView):
    model = Meeting
    template_name = 'management_system/detail/meeting_detail.html'
    form_class = MeetingForm
    success_url = reverse_lazy("management_system:meeting")

    def get_form_kwargs(self):
        meeting = self.get_object()
        user = self.request.user
        kwargs = super(MeetingDetailView, self).get_form_kwargs()
        if user.role != 'admin' and meeting.creator != user:
            kwargs.update({'readonly': True})
        return kwargs

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if request.POST.get("action") == "delete":
            self.object.delete()
            return redirect("management_system:meeting")
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_context_data(self, **kwargs):
        meeting = self.get_object()
        user = self.request.user
        context = super().get_context_data(**kwargs)
        if user.role != 'admin' and meeting.creator != user:
            context["readonly"] = True
        return context


class MeetingCreateView(CreateView):
    model = Meeting
    fields = ["name", "comments", "day", "time"]
    template_name = 'management_system/create/meet_create.html'
    success_url = reverse_lazy("management_system:meeting")

    def get_context_data(self, **kwargs):
        data = super(MeetingCreateView, self).get_context_data(**kwargs)
        if self.request.POST:
            data['meeting'] = MeetingMemberFormSet(self.request.POST)
        else:
            data['meeting'] = MeetingMemberFormSet()
        return data

    def form_valid(self, form):
        form.instance.creator = self.request.user
        context = self.get_context_data()
        meeting = context['meeting']
        if form.is_valid() and meeting.is_valid():
            self.object = form.save(commit=False)
        with transaction.atomic():
            self.object.save()
            meeting.instance = self.object
            meeting.save()
        return super(MeetingCreateView, self).form_valid(form)


class TaskListView(View):
    def get(self, request, *args, **kwargs):
        if not hasattr(request, "user") or isinstance(request.user, AnonymousUser):
            return redirect("management_system:login")
        user_tasks = Task.objects.filter(Q(executor=request.user) | Q(creator=request.user))
        context = {"tasks": user_tasks}
        return render(request, 'management_system/list/task_list.html', context=context)


class TaskDetailView(ModelFormMixin, DetailView):
    model = Task
    template_name = 'management_system/detail/task_detail.html'
    form_class = TaskForm
    success_url = reverse_lazy("management_system:task")

    def get_form_kwargs(self):
        task = self.get_object()
        user = self.request.user
        kwargs = super(TaskDetailView, self).get_form_kwargs()
        if user.role != 'admin' and task.creator != user:
            kwargs.update({'readonly': True})
        return kwargs

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if request.POST.get("action") == "delete":
            self.object.delete()
            return redirect("management_system:task")
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_context_data(self, **kwargs):
        task = self.get_object()
        user = self.request.user
        context = super().get_context_data(**kwargs)
        if user.role != 'admin' and task.creator != user:
            context["readonly"] = True
        return context


class TaskCreateView(CreateView):
    form_class = TaskForm
    template_name = 'management_system/detail/task_detail.html'
    success_url = reverse_lazy("management_system:task")

    def form_valid(self, form):
        form.instance.creator = self.request.user
        return super().form_valid(form)


class TeamListView(View):
    def get(self, request, *args, **kwargs):
        if not hasattr(request, "user") or isinstance(request.user, AnonymousUser):
            return redirect("management_system:login")
        user_teams = UserTeam.objects.filter(user=request.user)
        context = {"user_teams": user_teams}
        return render(request, 'management_system/list/team_list.html', context=context)


class TeamDetailView(DetailView):
    model = Team
    template_name = 'management_system/detail/team_detail.html'

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if request.POST.get("action") == "update":
            new_team_name = request.POST.get('name')
            self.object.name = new_team_name
            self.object.save()
        elif request.POST.get("action") == "delete":
            self.object.delete()
        return redirect("management_system:team")

    def get_context_data(self, **kwargs):
        team = self.get_object()
        user = self.request.user
        context = super().get_context_data(**kwargs)
        if user.role != 'admin' and team.owner != user:
            context["readonly"] = True
        return context


class TeamCreateView(CreateView):
    model = Team
    fields = ["name"]
    template_name = 'management_system/create/team_create.html'
    success_url = reverse_lazy("management_system:team")

    def get_context_data(self, **kwargs):
        data = super(TeamCreateView, self).get_context_data(**kwargs)
        if self.request.POST:
            data['members'] = TeamMemberFormSet(self.request.POST)
        else:
            data['members'] = TeamMemberFormSet()
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        members = context['members']
        if form.is_valid() and members.is_valid():
            form.instance.owner = self.request.user
            self.object = form.save(commit=False)
        with transaction.atomic():
            self.object.save()
            members.instance = self.object
            members.save()
        return super(TeamCreateView, self).form_valid(form)


class EvaluationListView(View):
    def get(self, request, *args, **kwargs):
        if not hasattr(request, "user") or isinstance(request.user, AnonymousUser):
            return redirect("management_system:login")
        evaluations = Evaluation.objects.filter(user=request.user)
        context = {"evaluations": evaluations}
        today = date.today()
        year_start = date(today.year, 1, 1)
        data = (Evaluation.objects
                .filter(updated_at__range=(year_start, today))
                .annotate(month=DateToChar(TruncMonth('updated_at')))
                .values('month')
                .annotate(avg_mark=Avg('mark')))
        context["average_marks"] = data

        return render(request, 'management_system/list/evaluation_list.html', context=context)


class EvaluationDetailView(ModelFormMixin, DetailView):
    model = Evaluation
    template_name = 'management_system/detail/evaluation_detail.html'
    form_class = EvaluationForm
    success_url = reverse_lazy("management_system:evaluation")

    def get_form_kwargs(self):
        evaluation = self.get_object()
        user = self.request.user
        kwargs = super(EvaluationDetailView, self).get_form_kwargs()
        if user.role != 'admin' and evaluation.task.creator != user:
            kwargs.update({'readonly': True})
        return kwargs

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()

app/app/src/management_system/templates/management_system/list/evaluation_list.html
{% extends 'base.html' %}

{% block body %}
<h3>Оценки</h3>
<table class="table">
  <thead>
    <tr style="width: 300px;">
      <th>Задача</th>
      <th>Описание</th>
      <th>Оценка</th>
      <th>Дата оценки</th>
    </tr>
  </thead>
  <tbody>
  {% if evaluations %}
    {% for evaluation in evaluations %}
      <tr class="formset_row" style="width: 300px;">
        <td><a href="{% url 'management_system:evaluation_detail' pk=evaluation.id %}">{{ evaluation.task }}</a></td>
        <td>{{ evaluation.task.description }}</td>
        <td>{{ evaluation.mark }}</td>
        <td>{{ evaluation.created_at }}</td>
      </tr>
    {% endfor %}
  {% else %}
    <p>Вы ещё не выполнили ни одной задачи</p>
  {% endif %}
  </tbody>
</table>
<br><br>
<h3>Средние оценки по месяцам</h3>
<table class="table">
  <thead>
    <tr style="width: 300px;">
      <th>Месяц</th>
      <th>Средняя оценка</th>
    </tr>
  </thead>
  <tbody>
    {% for average_mark in average_marks %}
      <tr class="formset_row" style="width: 300px;">
        <td>{{ average_mark.month }}</td>
        <td>{{ average_mark.avg_mark }}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>
<br><br>
  {% if user.role != "worker" %}
    <button class="btn btn-primary" id="evaluationCreate">
      <a href="{% url 'management_system:evaluation_create'%}" style="color:white;">Поставить оценку задаче</a>
    </button>
  {% endif %}
{% endblock %}

app/app/src/management_system/templates/management_system/list/meeting_list.html
{% extends 'base.html' %}

{% block body %}
<h3>Встречи</h3>
<table class="table">
  <thead>
    <tr style="width: 300px;">
      <th>Название встречи</th>
      <th>Дата</th>
      <th>Время</th>
    </tr>
  </thead>
  <tbody>
  {% if meetings %}
    {% for meeting in meetings %}
      <tr class="formset_row" style="width: 300px;">
        <td><a href="{% url 'management_system:meeting_detail' pk=meeting.id %}">{{ meeting.name }}</a></td>
        <td>{{ meeting.day }}</td>
        <td>{{ meeting.time }}</td>
      </tr>
    {% endfor %}
  {% else %}
    <p>У вас нет назначенных встреч</p>
  {% endif %}
  </tbody>
</table>
{% if user.role != "worker" %}
 <button class="btn btn-primary" id="meetingCreate">
    <a href="{% url 'management_system:meeting_create'%}" style="color:white;">Создать встречу</a>
  </button>
{% endif %}
{% endblock %}

app/app/src/management_system/templates/management_system/list/task_list.html
{% extends 'base.html' %}

{% block body %}
<h3>Задачи</h3>
<table class="table">
  <thead>
    <tr style="width: 300px;">
      <th>Название</th>
      <th>Описание</th>
      <th>Дедлайн</th>
    </tr>
  </thead>
  <tbody>
  {% if tasks %}
    {% for task in tasks %}
      <tr class="formset_row" style="width: 300px;">
        <td><a href="{% url 'management_system:task_detail' pk=task.id %}">{{ task.name }}</a></td>
        <td>{{ task.description }}</td>
        <td>{{ task.deadline }}</td>
      </tr>
    {% endfor %}
  {% else %}
    <p>Задач не назначено</p>
  {% endif %}
  </tbody>
</table>
<br><br>
  {% if user.role != "worker" %}
    <button class="btn btn-primary" id="taskCreate">
      <a href="{% url 'management_system:task_create'%}" style="color:white;">Создать задачу</a>
    </button>
  {% endif %}
{% endblock %}

app/app/src/management_system/templates/management_system/list/team_list.html
{% extends 'base.html' %}

{% block body %}
<h3>Команды</h3>
<table class="table">
  <thead>
    <tr style="width: 300px;">
      <th>Название команды</th>
      <th>Роль</th>
    </tr>
  </thead>
  <tbody>
  {% if user_teams %}
    {% for user_team in user_teams %}
      <tr class="formset_row" style="width: 300px;">
        <td><a href="{% url 'management_system:team_detail' pk=user_team.team.id %}">{{ user_team.team }}</a></td>
        <td>{{ user_team.position }}</td>
      </tr>
    {% endfor %}
  {% else %}
    <p>Вы не состоите в команде</p>
  {% endif %}
  </tbody>
</table>
<br><br>
{% if user.role != "worker" %}
  <button class="btn btn-primary" id="teamCreate">
    <a href="{% url 'management_system:team_create'%}" style="color:white;">Создать команду</a>
  </button>
{% endif %}
{% endblock %}